name: Vet

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  vet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.92.0"

      - uses: Swatinem/rust-cache@v2.9.1

      - name: Run vet
        run: bash scripts/vet.sh
